data_loader_config:
  train_batch_size: 128
  test_batch_size: 128
  val_batch_size: 128

# Use ADAM optimizer by default
optimizer_config:
  lr: 0.0001

# Use ReduceLROnPlateau scheduler by default
scheduler_config:
  mode: "min"
  factor: 0.2
  patience: 7
  threshold: 0.01
  threshold_mode: "rel"
  cooldown: 0
  min_lr: 0.000000001
  eps: 1e-08
  verbose: True



