age_labels_to_bins:
  0: (0, 12)
  1: (13, 17)
  2: (18, 29)
  3: (30, 39)
  4: (40, 49)
  5: (50, 59)
  6: (60, 69)
  7: (70, 120)
resnet_backbone: "resnet18"
pretrained: True
freeze_starting_layers: False