data_loader_config:
  train_batch_size: 128
  test_batch_size: 128
  val_batch_size: 128

# Use ADAM optimizer by default
optimizer_config:
  lr: 0.1

# Use ReduceLROnPlateau scheduler by default
scheduler_config:
  mode: "min"
  factor: 0.5
  patience: 5
  threshold: 0.1
  threshold_mode: "rel"
  cooldown: 0
  min_lr: 0
  eps: 1e-08
  verbose: True



